name: CI
on: [push, pull_request]
jobs:
  ci:
    strategy:
      matrix:
        platform: [x86, x64]
    runs-on: windows-latest
    steps:
      - name: Install Cygwin packages
        uses: egor-tensin/setup-cygwin@v2
        with:
          platform: ${{ matrix.platform }}
          packages: git cygport docbook-xsl perl-IPC-Run libxslt
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate cygcheck output
        run: |
          C:\tools\cygwin\bin\bash.exe -c 'cygcheck -srv >/var/log/cygcheck.out'
        if: always()
      - name: Store Chocolatey logs
        uses: actions/upload-artifact@v2
        with:
          name: choco-logs-${{ matrix.platform }}
          path: 'C:\ProgramData\chocolatey\logs\'
        if: always()
      - name: Store Cygwin logs
        uses: actions/upload-artifact@v2
        with:
          name: cygwin-logs-${{ matrix.platform }}
          path: 'C:\tools\cygwin\var\log\'
        if: always()
      - name: Cygport download
        run: |
          C:\tools\cygwin\bin\bash.exe -c 'cygport moreutils.cygport download'
      - name: Cygport prep
        run: |
          C:\tools\cygwin\bin\bash.exe -c 'cygport moreutils.cygport prep'
      - name: Cygport compile
        run: |
          C:\tools\cygwin\bin\bash.exe -c 'cygport moreutils.cygport compile'
      - name: Cygport test
        run: |
          C:\tools\cygwin\bin\bash.exe -c 'cygport moreutils.cygport test'
      - name: Cygport install
        run: |
          C:\tools\cygwin\bin\bash.exe -c 'cygport moreutils.cygport install'
      - name: Cygport package
        run: |
          C:\tools\cygwin\bin\bash.exe -c 'cygport moreutils.cygport package'
      - name: Cygport upload
        env:
          MAINTAINER_KEY: ${{ secrets.MAINTAINER_KEY }}
        run: |
          C:\tools\cygwin\bin\bash.exe -c 'umask 0077 && mkdir -p ~/.ssh'
          C:\tools\cygwin\bin\bash.exe -c 'umask 0077 && echo ""$MAINTAINER_KEY"" >~/.ssh/id_rsa'
          C:\tools\cygwin\bin\bash.exe -c 'umask 0077 && echo ""cygwin.com,8.43.85.97 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGqrxexIuyqmCVe33p1HuhUFzsXte5QZKb+BJlsRrvXOpUOJEW2S0kszyAiymeV7AXaYmHDKVRJpGVR+0ua0Xww="" >~/.ssh/known_hosts'
          C:\tools\cygwin\bin\bash.exe -c 'SSH_KEY=~/.ssh/id_rsa cygport moreutils.cygport upload'
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Tar up build results
        run: |
          C:\tools\cygwin\bin\bash.exe -c 'tar -caf moreutils-${{ matrix.platform }}.txz moreutils-*-*.*/'
        if: always()
      - name: Store build results
        uses: actions/upload-artifact@v2
        with:
          name: build-results-${{ matrix.platform }}
          path: |
            moreutils-${{ matrix.platform }}.txz
          if-no-files-found: error
        if: always()
