name: CI
on: [push, pull_request]
jobs:

  build-test:
    strategy:
      matrix:
        platform: [x86, x64]
    runs-on: windows-latest
    defaults:
      run:
        shell: bash --noprofile --norc -e -o pipefail -o igncr {0}
    env:
      PATH: C:\cygwin\bin
    steps:
      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@ad81540ad7c2726e17c08401fbeca6380cc7f463
        with:
          platform: ${{ matrix.platform }}
          packages: cygport git docbook-xsl libxslt perl-IPC-Run xz
        timeout-minutes: 10
      - name: Manually configure safe.directory
        run: git config --global --add safe.directory '*'
        timeout-minutes: 1
      - name: Checkout
        uses: actions/checkout@v3
        with:
          set-safe-directory: false  # actions/checkout otherwise tries to use the wrong config file, per actions/checkout#767
        timeout-minutes: 1
      - name: Generate cygcheck output
        if: always()
        run: cygcheck -srv >/var/log/cygcheck.out
        timeout-minutes: 5
      - name: Store Cygwin logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cygwin-logs-${{ matrix.platform }}
          path: 'C:\cygwin\var\log\'
        timeout-minutes: 5
      - name: Cygport download
        run: cygport moreutils.cygport download
        timeout-minutes: 5
      - name: Cygport prep
        run: cygport moreutils.cygport prep
        timeout-minutes: 1
      - name: Cygport compile
        run: cygport moreutils.cygport compile
        timeout-minutes: 30
      - name: Cygport test
        run: cygport moreutils.cygport test
        timeout-minutes: 300
      - name: Cygport install
        run: cygport moreutils.cygport install
        timeout-minutes: 30
      - name: Cygport package
        run: cygport moreutils.cygport package
        timeout-minutes: 5
      - name: Configure SSH
        if: github.ref == 'refs/heads/main'
        env:
          MAINTAINER_KEY: ${{ secrets.MAINTAINER_KEY }}
        run: |
          umask 0077
          mkdir -p ~/.ssh
          echo "$MAINTAINER_KEY" >~/.ssh/id_rsa
          echo 'cygwin.com,8.43.85.97 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGqrxexIuyqmCVe33p1HuhUFzsXte5QZKb+BJlsRrvXOpUOJEW2S0kszyAiymeV7AXaYmHDKVRJpGVR+0ua0Xww=' >~/.ssh/known_hosts
        timeout-minutes: 1
      - name: Cygport stage
        if: github.ref == 'refs/heads/main'
        run: SSH_KEY=~/.ssh/id_rsa cygport moreutils.cygport stage
        timeout-minutes: 5
      - name: Tar up build results
        if: always()
        run: tar -caf moreutils-${{ matrix.platform }}.txz moreutils-*-*.*/
        timeout-minutes: 10
      - name: Store build results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-results-${{ matrix.platform }}
          path: moreutils-${{ matrix.platform }}.txz
          if-no-files-found: error
        timeout-minutes: 5

  release:
    if: github.ref == 'refs/heads/main'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install lftp
        timeout-minutes: 5
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        timeout-minutes: 1
      - name: Compute release name
        id: release-name
        run: |
          eval $(grep -e '^VERSION=' -e '^RELEASE=' moreutils.cygport)
          printf '::set-output name=release::%s-%s' "$VERSION" "$RELEASE"
        timeout-minutes: 1
      - name: Download build results
        uses: actions/download-artifact@v2
        timeout-minutes: 5
      - name: Unpack build results
        run: |
          tar -xaf build-results-x86/moreutils-x86.txz
          tar -xaf build-results-x64/moreutils-x64.txz
        timeout-minutes: 5
      - name: Name release artifacts for the GitHub release
        env:
          PVR: ${{ steps.release-name.outputs.release }}
        run: |
          (
            cd "moreutils-${PVR}.i686/dist/moreutils" &&
            rm "moreutils-${PVR}-src".* &&
            mv "moreutils-${PVR}.hint" "moreutils-${PVR}.i686.hint" &&
            mv "moreutils-${PVR}.tar.xz" "moreutils-${PVR}.i686.tar.xz"
          )
          (
            cd "moreutils-${PVR}.x86_64/dist/moreutils" &&
            mv "moreutils-${PVR}.hint" "moreutils-${PVR}.x86_64.hint" &&
            mv "moreutils-${PVR}.tar.xz" "moreutils-${PVR}.x86_64.tar.xz"
          )
        timeout-minutes: 1
      - name: Create release tag
        env:
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
        run: |
          git tag -am 'v${{ steps.release-name.outputs.release }}' 'v${{ steps.release-name.outputs.release }}'
          git push origin tag 'v${{ steps.release-name.outputs.release }}'
        timeout-minutes: 1
      - name: Create a GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.release-name.outputs.release }}-test
          files: moreutils-*/dist/moreutils/*
          target_commitish: ${{ github.ref }}
        timeout-minutes: 2
      - name: Configure SSH
        env:
          MAINTAINER_KEY: ${{ secrets.MAINTAINER_KEY }}
        run: |
          umask 0077
          mkdir -p ~/.ssh
          echo "$MAINTAINER_KEY" >~/.ssh/id_rsa
          echo 'cygwin.com,8.43.85.97 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGqrxexIuyqmCVe33p1HuhUFzsXte5QZKb+BJlsRrvXOpUOJEW2S0kszyAiymeV7AXaYmHDKVRJpGVR+0ua0Xww=' >~/.ssh/known_hosts
        timeout-minutes: 1
      - name: Mirror to Cygwin Git repositories
        if: false
        run: git push cygwin@cygwin.com:/git/cygwin-packages/moreutils 'v${{ steps.release-name.outputs.release }}'
        timeout-minutes: 5
      - name: Release on the Cygwin mirror
        run: >
          lftp -c 'set cmd:fail-exit on;
                   set cmd:interactive on;
                   set net:max-retries 1;
                   open sftp://cygwin:@cygwin.com;
                   put /dev/null -o /x86/release/moreutils/!ready;
                   put /dev/null -o /x86_64/release/moreutils/!ready;'
        timeout-minutes: 5
